<a href="https://colab.research.google.com/github/Jagadeesh-krishna/program/blob/main/aggregate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [22]:
df=pd.read_excel("/content/drive/MyDrive/data science/student_dataset_20rows.xlsx")

In [5]:
df.head()

   Student_ID   Name  Age        Course  Marks        City
0         101    Ram   25        Pandas     90  Vijayawada
1         102   Ravi   23         NumPy     81   Hyderabad
2         103   Sita   21        Python     80     Chennai
3         104  Kiran   21  Data Science     98   Bangalore
4         105    Anu   20        Pandas     70      Mumbai

In [6]:
print(df["Marks"].sum()) #sum: it will calculates sum all the data in that column

1656

In [7]:
print(df["Marks"].mean()) #calculates the mean

82.8

In [8]:
print(df["Marks"].median()) # calculates the median

81.0

In [9]:
print(df["Marks"].min()) # show the min value

70

In [10]:
df["Marks"].max()

99

In [11]:
df["Marks"].count()

np.int64(20)

In [13]:
df["Marks"].std()

10.076549116898263

In [14]:
df["Marks"].var()

101.53684210526318

In [ ]:
df["Marks"].describe()

In [ ]:
df["Marks"].agg(["sum","mean"])

In [19]:
import seaborn as sns
import pandas as pd
# Load dataset
df = sns.load_dataset("tips")
# Display first 5 rows
print(df.head())

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [18]:
df["total_bill"].sum()

np.float64(4827.77)

In [27]:
g=df.groupby("city")

In [28]:
for city, city_df in g:
  print(city)
  print(city_df)

mumbai
        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain
new york
        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny
paris
         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [ ]:
g.get_group("mumbai")

In [30]:
df.columns

Index(['day', 'city', 'temperature', 'windspeed', 'event'], dtype='object')

In [32]:
df.groupby("city")["temperature"].max()

city
mumbai      92
new york    36
paris       54
Name: temperature, dtype: int64

In [33]:
# find average wind speed per city
df.groupby("city")["windspeed"].mean()

city
mumbai       9.25
new york     8.00
paris       12.75
Name: windspeed, dtype: float64

In [34]:
df.groupby("city")["windspeed"].sum()

city
mumbai      37
new york    32
paris       51
Name: windspeed, dtype: int64

In [35]:
df.groupby("city")["windspeed"].max()

city
mumbai      15
new york    12
paris       20
Name: windspeed, dtype: int64